# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-rnassembly-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - conda-forge::r-data.table=1.12.2
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-markdown=0.9
  - matplotlib=3.0.3        # Current 3.1.0 build incompatible with multiqc=1.7

  ## bioconda packages
  - fastqc=0.11.8
  - seqkit=0.11.0
  - bedtools=2.29.0
  - gffutils=0.9
  - atropos=1.1.22
  - stringtie=1.3.6
  - samtools=1.9
  - gffread=0.11.4
  - pasa=2.3.3
  - hisat2=2.1.0
  - spades=3.13.1
  - hmmer=3.2.1
  - blast=2.9.0
  - multiqc=1.7
